Raising custom exceptions for REST errors.
CruGlobal/global_registry_client pull request #10
Opened 2020-03-30 14:48 UTC by ckozus

This will allow applications using this gem to specifically rescue and ignore RestClient exceptions coming from this gem and not all RestClient exceptions.

2020-03-30 15:14 UTC, soberstadt requested changes
Could you add an expectations array to lib/global_registry/exceptions.rb so that we can do something like
```ruby
rescue *GlobalRegistry::EXCEPTIONS => error
```

see https://thoughtbot.com/blog/rescue-standarderror-not-exception#best-case-scenario

2020-03-30 15:27 UTC, ckozus commented
> Could you add an expectations array to lib/global_registry/exceptions.rb so that we can do something like
> 
> ```ruby
> rescue *GlobalRegistry::EXCEPTIONS => error
> ```
> 
> see https://thoughtbot.com/blog/rescue-standarderror-not-exception#best-case-scenario

@soberstadt done!

2020-03-30 15:31 UTC, soberstadt commented on lib/global_registry/exceptions.rb
> +
```suggestion
```

2020-03-30 15:40 UTC, soberstadt approved these changes
Great! I think this will be a non-breaking change because the consumers of this gem will still be able to rescue the `RestClient` super-class exceptions (see image attached). I recommend merging this with a minor version number bump.

![image](https://user-images.githubusercontent.com/1080613/77932158-283f4380-727b-11ea-9a1a-7dd54b4b4f1f.png)

2020-03-30 15:41 UTC, soberstadt commented
@knutsenm you good with these changes?

2020-04-01 18:04 UTC, knutsenm approved these changes

2020-04-01 18:31 UTC, merged